info:
    app:
        description: Master Spring Boot
        name: Spring Boot Demo App
        version: 1.0.0
    company:
        name: Aurelchivu
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        password: ''
        url: jdbc:postgresql://localhost:5432/springdemo
        username: ''
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    main:
        banner-mode: 'off'
